// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bots.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBots = `-- name: CountBots :one
SELECT COUNT(*) FROM bots
WHERE
    ($1::varchar IS NULL OR rig_id = $1) AND
    ($2::boolean IS NULL OR kill_switch = $2) AND
    ($3::varchar IS NULL OR last_run_log ILIKE '%' || $3 || '%') AND
    ($4::timestamptz IS NULL OR create_at >= $4) AND
    ($5::timestamptz IS NULL OR create_at <= $5) AND
    ($6::timestamptz IS NULL OR last_update_at >= $6) AND
    ($7::timestamptz IS NULL OR last_update_at <= $7) AND
    ($8::timestamptz IS NULL OR last_run_at >= $8) AND
    ($9::timestamptz IS NULL OR last_run_at <= $9)
`

type CountBotsParams struct {
	RigID            pgtype.Text `json:"rig_id"`
	KillSwitch       pgtype.Bool `json:"kill_switch"`
	LogSearch        pgtype.Text `json:"log_search"`
	CreateAtFrom     *time.Time  `json:"create_at_from"`
	CreateAtTo       *time.Time  `json:"create_at_to"`
	LastUpdateAtFrom *time.Time  `json:"last_update_at_from"`
	LastUpdateAtTo   *time.Time  `json:"last_update_at_to"`
	LastRunAtFrom    *time.Time  `json:"last_run_at_from"`
	LastRunAtTo      *time.Time  `json:"last_run_at_to"`
}

func (q *Queries) CountBots(ctx context.Context, arg CountBotsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBots,
		arg.RigID,
		arg.KillSwitch,
		arg.LogSearch,
		arg.CreateAtFrom,
		arg.CreateAtTo,
		arg.LastUpdateAtFrom,
		arg.LastUpdateAtTo,
		arg.LastRunAtFrom,
		arg.LastRunAtTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBot = `-- name: CreateBot :one
INSERT INTO bots (id, rig_id, kill_switch, last_run_log, create_at, last_update_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, rig_id, last_run_at, kill_switch, last_run_log, create_at, last_update_at
`

type CreateBotParams struct {
	ID         string      `json:"id"`
	RigID      string      `json:"rig_id"`
	KillSwitch bool        `json:"kill_switch"`
	LastRunLog pgtype.Text `json:"last_run_log"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.ID,
		arg.RigID,
		arg.KillSwitch,
		arg.LastRunLog,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.RigID,
		&i.LastRunAt,
		&i.KillSwitch,
		&i.LastRunLog,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const deleteBot = `-- name: DeleteBot :exec
DELETE FROM bots WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBot, id)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, rig_id, last_run_at, kill_switch, last_run_log, create_at, last_update_at FROM bots WHERE id = $1
`

func (q *Queries) GetBotByID(ctx context.Context, id string) (Bot, error) {
	row := q.db.QueryRow(ctx, getBotByID, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.RigID,
		&i.LastRunAt,
		&i.KillSwitch,
		&i.LastRunLog,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const listBots = `-- name: ListBots :many
SELECT id, rig_id, last_run_at, kill_switch, last_run_log, create_at, last_update_at FROM bots
WHERE
    ($3::varchar IS NULL OR rig_id = $3) AND
    ($4::boolean IS NULL OR kill_switch = $4) AND
    ($5::varchar IS NULL OR last_run_log ILIKE '%' || $5 || '%') AND
    ($6::timestamptz IS NULL OR create_at >= $6) AND
    ($7::timestamptz IS NULL OR create_at <= $7) AND
    ($8::timestamptz IS NULL OR last_update_at >= $8) AND
    ($9::timestamptz IS NULL OR last_update_at <= $9) AND
    ($10::timestamptz IS NULL OR last_run_at >= $10) AND
    ($11::timestamptz IS NULL OR last_run_at <= $11)
ORDER BY create_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListBotsParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	RigID            pgtype.Text `json:"rig_id"`
	KillSwitch       pgtype.Bool `json:"kill_switch"`
	LogSearch        pgtype.Text `json:"log_search"`
	CreateAtFrom     *time.Time  `json:"create_at_from"`
	CreateAtTo       *time.Time  `json:"create_at_to"`
	LastUpdateAtFrom *time.Time  `json:"last_update_at_from"`
	LastUpdateAtTo   *time.Time  `json:"last_update_at_to"`
	LastRunAtFrom    *time.Time  `json:"last_run_at_from"`
	LastRunAtTo      *time.Time  `json:"last_run_at_to"`
}

func (q *Queries) ListBots(ctx context.Context, arg ListBotsParams) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listBots,
		arg.Limit,
		arg.Offset,
		arg.RigID,
		arg.KillSwitch,
		arg.LogSearch,
		arg.CreateAtFrom,
		arg.CreateAtTo,
		arg.LastUpdateAtFrom,
		arg.LastUpdateAtTo,
		arg.LastRunAtFrom,
		arg.LastRunAtTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.RigID,
			&i.LastRunAt,
			&i.KillSwitch,
			&i.LastRunLog,
			&i.CreateAt,
			&i.LastUpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBot = `-- name: UpdateBot :one
UPDATE bots
SET rig_id = COALESCE($2, rig_id),
    kill_switch = COALESCE($3, kill_switch),
    last_run_log = COALESCE($4, last_run_log),
    last_run_at = COALESCE($5, last_run_at),
    last_update_at = NOW()
WHERE id = $1
RETURNING id, rig_id, last_run_at, kill_switch, last_run_log, create_at, last_update_at
`

type UpdateBotParams struct {
	ID         string      `json:"id"`
	RigID      pgtype.Text `json:"rig_id"`
	KillSwitch pgtype.Bool `json:"kill_switch"`
	LastRunLog pgtype.Text `json:"last_run_log"`
	LastRunAt  *time.Time  `json:"last_run_at"`
}

func (q *Queries) UpdateBot(ctx context.Context, arg UpdateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, updateBot,
		arg.ID,
		arg.RigID,
		arg.KillSwitch,
		arg.LastRunLog,
		arg.LastRunAt,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.RigID,
		&i.LastRunAt,
		&i.KillSwitch,
		&i.LastRunLog,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}
