// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFailedTask = `-- name: CreateFailedTask :one
INSERT INTO failed_tasks (
    original_task_id,
    task_type,
    payload,
    error_message,
    error_stack,
    attempt_count,
    final_attempt_at,
    create_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
ON CONFLICT (original_task_id) DO UPDATE SET
    task_type = EXCLUDED.task_type,
    payload = EXCLUDED.payload,
    error_message = EXCLUDED.error_message,
    error_stack = EXCLUDED.error_stack,
    attempt_count = EXCLUDED.attempt_count,
    final_attempt_at = EXCLUDED.final_attempt_at
RETURNING id, original_task_id, task_type, payload, error_message, error_stack, attempt_count, final_attempt_at, create_at
`

type CreateFailedTaskParams struct {
	OriginalTaskID string      `json:"original_task_id"`
	TaskType       string      `json:"task_type"`
	Payload        []byte      `json:"payload"`
	ErrorMessage   string      `json:"error_message"`
	ErrorStack     pgtype.Text `json:"error_stack"`
	AttemptCount   int32       `json:"attempt_count"`
}

func (q *Queries) CreateFailedTask(ctx context.Context, arg CreateFailedTaskParams) (FailedTask, error) {
	row := q.db.QueryRow(ctx, createFailedTask,
		arg.OriginalTaskID,
		arg.TaskType,
		arg.Payload,
		arg.ErrorMessage,
		arg.ErrorStack,
		arg.AttemptCount,
	)
	var i FailedTask
	err := row.Scan(
		&i.ID,
		&i.OriginalTaskID,
		&i.TaskType,
		&i.Payload,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.AttemptCount,
		&i.FinalAttemptAt,
		&i.CreateAt,
	)
	return i, err
}
