// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID           string      `json:"id"`
	RigID        string      `json:"rig_id"`
	LastRunAt    *time.Time  `json:"last_run_at"`
	KillSwitch   bool        `json:"kill_switch"`
	LastRunLog   pgtype.Text `json:"last_run_log"`
	CreateAt     time.Time   `json:"create_at"`
	LastUpdateAt time.Time   `json:"last_update_at"`
}

type FailedTask struct {
	ID             int64       `json:"id"`
	OriginalTaskID string      `json:"original_task_id"`
	TaskType       string      `json:"task_type"`
	Payload        []byte      `json:"payload"`
	ErrorMessage   string      `json:"error_message"`
	ErrorStack     pgtype.Text `json:"error_stack"`
	AttemptCount   int32       `json:"attempt_count"`
	FinalAttemptAt time.Time   `json:"final_attempt_at"`
	CreateAt       time.Time   `json:"create_at"`
}

type ScheduledJob struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	JobType        string      `json:"job_type"`
	Payload        []byte      `json:"payload"`
	CronExpression string      `json:"cron_expression"`
	NextRunAt      *time.Time  `json:"next_run_at"`
	LastRunAt      *time.Time  `json:"last_run_at"`
	Enabled        bool        `json:"enabled"`
	LastError      pgtype.Text `json:"last_error"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type SessionToken struct {
	TokenJti       string      `json:"token_jti"`
	UserID         string      `json:"user_id"`
	IssuedAt       time.Time   `json:"issued_at"`
	ExpiresAt      time.Time   `json:"expires_at"`
	RevokedAt      *time.Time  `json:"revoked_at"`
	RotatedFromJti pgtype.Text `json:"rotated_from_jti"`
	UserAgentHash  pgtype.Text `json:"user_agent_hash"`
	IpSubnet       pgtype.Text `json:"ip_subnet"`
}

type Task struct {
	ID                  string      `json:"id"`
	Type                string      `json:"type"`
	Payload             []byte      `json:"payload"`
	Status              string      `json:"status"`
	Result              []byte      `json:"result"`
	Error               pgtype.Text `json:"error"`
	RetryCount          int32       `json:"retry_count"`
	ProcessingStartedAt *time.Time  `json:"processing_started_at"`
	CompletedAt         *time.Time  `json:"completed_at"`
	CreateAt            time.Time   `json:"create_at"`
	LastUpdateAt        time.Time   `json:"last_update_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsActive     bool      `json:"is_active"`
	IsAdmin      bool      `json:"is_admin"`
	CreateAt     time.Time `json:"create_at"`
	LastUpdateAt time.Time `json:"last_update_at"`
}

type Webhook struct {
	ID           string          `json:"id"`
	UserID       string          `json:"user_id"`
	TargetUrl    string          `json:"target_url"`
	Secret       string          `json:"secret"`
	EventTypes   json.RawMessage `json:"event_types"`
	IsActive     bool            `json:"is_active"`
	CreateAt     time.Time       `json:"create_at"`
	LastUpdateAt time.Time       `json:"last_update_at"`
}

type WebhookDeliveryLog struct {
	ID           string      `json:"id"`
	WebhookID    string      `json:"webhook_id"`
	EventID      string      `json:"event_id"`
	EventType    string      `json:"event_type"`
	Success      bool        `json:"success"`
	Attempts     int32       `json:"attempts"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody pgtype.Text `json:"response_body"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreateAt     time.Time   `json:"create_at"`
}
