// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_jobs.sql

package sqlc

import (
	"context"
	"time"
)

const getScheduledJobForUpdate = `-- name: GetScheduledJobForUpdate :one
SELECT id, name, task_type, task_payload, cron_expression, next_run_at, is_enabled, create_at, last_update_at
FROM scheduled_jobs
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetScheduledJobForUpdate(ctx context.Context, id string) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJobForUpdate, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaskType,
		&i.TaskPayload,
		&i.CronExpression,
		&i.NextRunAt,
		&i.IsEnabled,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const pickDueScheduledJobs = `-- name: PickDueScheduledJobs :many
SELECT id, name, task_type, task_payload, cron_expression, next_run_at, is_enabled, create_at, last_update_at
FROM scheduled_jobs
WHERE id IN (
    SELECT id
    FROM scheduled_jobs
    WHERE next_run_at <= NOW()
      AND is_enabled = TRUE
    ORDER BY next_run_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
ORDER BY next_run_at ASC
`

func (q *Queries) PickDueScheduledJobs(ctx context.Context, limit int32) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, pickDueScheduledJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaskType,
			&i.TaskPayload,
			&i.CronExpression,
			&i.NextRunAt,
			&i.IsEnabled,
			&i.CreateAt,
			&i.LastUpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledJobNextRunAt = `-- name: UpdateScheduledJobNextRunAt :one
UPDATE scheduled_jobs
SET next_run_at = $2,
    last_update_at = NOW()
WHERE id = $1
RETURNING id, name, task_type, task_payload, cron_expression, next_run_at, is_enabled, create_at, last_update_at
`

type UpdateScheduledJobNextRunAtParams struct {
	ID        string    `json:"id"`
	NextRunAt time.Time `json:"next_run_at"`
}

func (q *Queries) UpdateScheduledJobNextRunAt(ctx context.Context, arg UpdateScheduledJobNextRunAtParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, updateScheduledJobNextRunAt, arg.ID, arg.NextRunAt)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaskType,
		&i.TaskPayload,
		&i.CronExpression,
		&i.NextRunAt,
		&i.IsEnabled,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}
