// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_job_executions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScheduledJobExecution = `-- name: CompleteScheduledJobExecution :one
UPDATE scheduled_job_executions
SET completed_at = NOW(),
    success = $2,
    output = $3,
    error_message = $4
WHERE id = $1
RETURNING id, job_id, started_at, completed_at, success, output, error_message
`

type CompleteScheduledJobExecutionParams struct {
	ID           pgtype.UUID `json:"id"`
	Success      pgtype.Bool `json:"success"`
	Output       pgtype.Text `json:"output"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CompleteScheduledJobExecution(ctx context.Context, arg CompleteScheduledJobExecutionParams) (ScheduledJobExecution, error) {
	row := q.db.QueryRow(ctx, completeScheduledJobExecution,
		arg.ID,
		arg.Success,
		arg.Output,
		arg.ErrorMessage,
	)
	var i ScheduledJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Success,
		&i.Output,
		&i.ErrorMessage,
	)
	return i, err
}

const createScheduledJobExecution = `-- name: CreateScheduledJobExecution :one
INSERT INTO scheduled_job_executions (job_id, started_at)
VALUES ($1, NOW())
RETURNING id, job_id, started_at, completed_at, success, output, error_message
`

func (q *Queries) CreateScheduledJobExecution(ctx context.Context, jobID pgtype.UUID) (ScheduledJobExecution, error) {
	row := q.db.QueryRow(ctx, createScheduledJobExecution, jobID)
	var i ScheduledJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Success,
		&i.Output,
		&i.ErrorMessage,
	)
	return i, err
}

const listScheduledJobExecutionsByJobID = `-- name: ListScheduledJobExecutionsByJobID :many
SELECT id, job_id, started_at, completed_at, success, output, error_message
FROM scheduled_job_executions
WHERE job_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListScheduledJobExecutionsByJobIDParams struct {
	JobID pgtype.UUID `json:"job_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListScheduledJobExecutionsByJobID(ctx context.Context, arg ListScheduledJobExecutionsByJobIDParams) ([]ScheduledJobExecution, error) {
	rows, err := q.db.Query(ctx, listScheduledJobExecutionsByJobID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJobExecution{}
	for rows.Next() {
		var i ScheduledJobExecution
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Success,
			&i.Output,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
