// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM session_tokens
WHERE expires_at < NOW() - INTERVAL '1 day'
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createSessionToken = `-- name: CreateSessionToken :one
INSERT INTO session_tokens (token_jti, user_id, issued_at, expires_at, rotated_from_jti, user_agent_hash, ip_subnet)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING token_jti, user_id, issued_at, expires_at, revoked_at, rotated_from_jti, user_agent_hash, ip_subnet
`

type CreateSessionTokenParams struct {
	TokenJti       string      `json:"token_jti"`
	UserID         string      `json:"user_id"`
	IssuedAt       time.Time   `json:"issued_at"`
	ExpiresAt      time.Time   `json:"expires_at"`
	RotatedFromJti pgtype.Text `json:"rotated_from_jti"`
	UserAgentHash  pgtype.Text `json:"user_agent_hash"`
	IpSubnet       pgtype.Text `json:"ip_subnet"`
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) (SessionToken, error) {
	row := q.db.QueryRow(ctx, createSessionToken,
		arg.TokenJti,
		arg.UserID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RotatedFromJti,
		arg.UserAgentHash,
		arg.IpSubnet,
	)
	var i SessionToken
	err := row.Scan(
		&i.TokenJti,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedFromJti,
		&i.UserAgentHash,
		&i.IpSubnet,
	)
	return i, err
}

const getSessionByRotatedFrom = `-- name: GetSessionByRotatedFrom :one
SELECT token_jti, user_id, issued_at, expires_at, revoked_at, rotated_from_jti, user_agent_hash, ip_subnet FROM session_tokens WHERE rotated_from_jti = $1
`

func (q *Queries) GetSessionByRotatedFrom(ctx context.Context, rotatedFromJti pgtype.Text) (SessionToken, error) {
	row := q.db.QueryRow(ctx, getSessionByRotatedFrom, rotatedFromJti)
	var i SessionToken
	err := row.Scan(
		&i.TokenJti,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedFromJti,
		&i.UserAgentHash,
		&i.IpSubnet,
	)
	return i, err
}

const getSessionToken = `-- name: GetSessionToken :one
SELECT token_jti, user_id, issued_at, expires_at, revoked_at, rotated_from_jti, user_agent_hash, ip_subnet FROM session_tokens WHERE token_jti = $1
`

func (q *Queries) GetSessionToken(ctx context.Context, tokenJti string) (SessionToken, error) {
	row := q.db.QueryRow(ctx, getSessionToken, tokenJti)
	var i SessionToken
	err := row.Scan(
		&i.TokenJti,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedFromJti,
		&i.UserAgentHash,
		&i.IpSubnet,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT token_jti, user_id, issued_at, expires_at, revoked_at, rotated_from_jti, user_agent_hash, ip_subnet FROM session_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY issued_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID string) ([]SessionToken, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionToken{}
	for rows.Next() {
		var i SessionToken
		if err := rows.Scan(
			&i.TokenJti,
			&i.UserID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RotatedFromJti,
			&i.UserAgentHash,
			&i.IpSubnet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE session_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
  AND token_jti != $2
`

type RevokeAllUserSessionsParams struct {
	UserID   string `json:"user_id"`
	TokenJti string `json:"token_jti"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.TokenJti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserSessionsUnconditional = `-- name: RevokeAllUserSessionsUnconditional :exec
UPDATE session_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessionsUnconditional(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessionsUnconditional, userID)
	return err
}

const revokeSessionToken = `-- name: RevokeSessionToken :exec
UPDATE session_tokens
SET revoked_at = NOW()
WHERE token_jti = $1
`

func (q *Queries) RevokeSessionToken(ctx context.Context, tokenJti string) error {
	_, err := q.db.Exec(ctx, revokeSessionToken, tokenJti)
	return err
}
