// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'completed',
    result = $2,
    error = NULL,
    completed_at = NOW(),
    last_update_at = NOW()
WHERE id = $1
RETURNING id, type, payload, status, result, error, retry_count, processing_started_at, completed_at, create_at, last_update_at
`

type CompleteTaskParams struct {
	ID     string `json:"id"`
	Result []byte `json:"result"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.ID, arg.Result)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.RetryCount,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, type, payload, status, create_at, last_update_at)
VALUES ($1, $2, $3, 'queued', NOW(), NOW())
RETURNING id, type, payload, status, result, error, retry_count, processing_started_at, completed_at, create_at, last_update_at
`

type CreateTaskParams struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Payload []byte `json:"payload"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.ID, arg.Type, arg.Payload)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.RetryCount,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :one
UPDATE tasks
SET status = 'failed',
    error = $2,
    retry_count = retry_count + 1,
    last_update_at = NOW()
WHERE id = $1
RETURNING id, type, payload, status, result, error, retry_count, processing_started_at, completed_at, create_at, last_update_at
`

type FailTaskParams struct {
	ID    string      `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, failTask, arg.ID, arg.Error)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.RetryCount,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, type, payload, status, result, error, retry_count, processing_started_at, completed_at, create_at, last_update_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.RetryCount,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const pickQueuedTask = `-- name: PickQueuedTask :one
UPDATE tasks
SET status = 'processing',
    processing_started_at = NOW(),
    last_update_at = NOW()
WHERE id = (
    SELECT id FROM tasks
    WHERE (status = 'queued' OR (status = 'failed' AND retry_count < 3))
    ORDER BY create_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, type, payload, status, result, error, retry_count, processing_started_at, completed_at, create_at, last_update_at
`

func (q *Queries) PickQueuedTask(ctx context.Context) (Task, error) {
	row := q.db.QueryRow(ctx, pickQueuedTask)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.RetryCount,
		&i.ProcessingStartedAt,
		&i.CompletedAt,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const resetStaleTasks = `-- name: ResetStaleTasks :exec
UPDATE tasks
SET status = 'queued',
    processing_started_at = NULL,
    last_update_at = NOW()
WHERE status = 'processing'
  AND processing_started_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) ResetStaleTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStaleTasks)
	return err
}
