// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at
`

type CreateWebhookParams struct {
	ID         string          `json:"id"`
	UserID     string          `json:"user_id"`
	TargetUrl  string          `json:"target_url"`
	Secret     string          `json:"secret"`
	EventTypes json.RawMessage `json:"event_types"`
	IsActive   bool            `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.UserID,
		arg.TargetUrl,
		arg.Secret,
		arg.EventTypes,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypes,
		&i.IsActive,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const createWebhookDeliveryLog = `-- name: CreateWebhookDeliveryLog :one
INSERT INTO webhook_delivery_logs (id, webhook_id, event_id, event_type, success, attempts, status_code, response_body, error_message, create_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, webhook_id, event_id, event_type, success, attempts, status_code, response_body, error_message, create_at
`

type CreateWebhookDeliveryLogParams struct {
	ID           string      `json:"id"`
	WebhookID    string      `json:"webhook_id"`
	EventID      string      `json:"event_id"`
	EventType    string      `json:"event_type"`
	Success      bool        `json:"success"`
	Attempts     int32       `json:"attempts"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody pgtype.Text `json:"response_body"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateWebhookDeliveryLog(ctx context.Context, arg CreateWebhookDeliveryLogParams) (WebhookDeliveryLog, error) {
	row := q.db.QueryRow(ctx, createWebhookDeliveryLog,
		arg.ID,
		arg.WebhookID,
		arg.EventID,
		arg.EventType,
		arg.Success,
		arg.Attempts,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
	)
	var i WebhookDeliveryLog
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.EventType,
		&i.Success,
		&i.Attempts,
		&i.StatusCode,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.CreateAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypes,
		&i.IsActive,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const listActiveWebhooksByEventType = `-- name: ListActiveWebhooksByEventType :many
SELECT id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at FROM webhooks
WHERE is_active = TRUE
  AND event_types @> $1::jsonb
`

func (q *Queries) ListActiveWebhooksByEventType(ctx context.Context, eventTypeJson json.RawMessage) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksByEventType, eventTypeJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetUrl,
			&i.Secret,
			&i.EventTypes,
			&i.IsActive,
			&i.CreateAt,
			&i.LastUpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLogsByWebhookID = `-- name: ListDeliveryLogsByWebhookID :many
SELECT id, webhook_id, event_id, event_type, success, attempts, status_code, response_body, error_message, create_at FROM webhook_delivery_logs
WHERE webhook_id = $1
ORDER BY create_at DESC
LIMIT 100
`

func (q *Queries) ListDeliveryLogsByWebhookID(ctx context.Context, webhookID string) ([]WebhookDeliveryLog, error) {
	rows, err := q.db.Query(ctx, listDeliveryLogsByWebhookID, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDeliveryLog{}
	for rows.Next() {
		var i WebhookDeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.EventType,
			&i.Success,
			&i.Attempts,
			&i.StatusCode,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByUserID = `-- name: ListWebhooksByUserID :many
SELECT id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at FROM webhooks WHERE user_id = $1 ORDER BY create_at DESC
`

func (q *Queries) ListWebhooksByUserID(ctx context.Context, userID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetUrl,
			&i.Secret,
			&i.EventTypes,
			&i.IsActive,
			&i.CreateAt,
			&i.LastUpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET target_url = COALESCE($2, target_url),
    secret = COALESCE($3, secret),
    event_types = COALESCE($4, event_types),
    is_active = COALESCE($5, is_active),
    last_update_at = NOW()
WHERE id = $1
RETURNING id, user_id, target_url, secret, event_types, is_active, create_at, last_update_at
`

type UpdateWebhookParams struct {
	ID         string      `json:"id"`
	TargetUrl  pgtype.Text `json:"target_url"`
	Secret     pgtype.Text `json:"secret"`
	EventTypes []byte      `json:"event_types"`
	IsActive   pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.TargetUrl,
		arg.Secret,
		arg.EventTypes,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUrl,
		&i.Secret,
		&i.EventTypes,
		&i.IsActive,
		&i.CreateAt,
		&i.LastUpdateAt,
	)
	return i, err
}
